version: "3"
services:
  mariadb:
    restart: always
    privileged: true
    image: mariadb:11.1.3
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_allowed_packet=128M
      --default-time-zone=+8:00
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
